name: Terraform + AKS CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve


      - name: Azure CLI - Login again (for Docker + AKS)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & Push Docker Image to ACR
        run: |
          docker build -t fastapi-aks-app .
          az acr login --name acrgha12345
          docker tag fastapi-aks-app acrgha12345.azurecr.io/fastapi-aks-app:v1
          docker push acrgha12345.azurecr.io/fastapi-aks-app:v1

      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group rg-aks-gha --name aks-gha-cluster
          kubectl apply -f terraform/k8s/deployment.yaml
          kubectl apply -f terraform/k8s/service.yaml


